# Railway Nixpacks configuration
[variables]
PYTHONPATH = "/app"

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[start]
cmd = "gunicorn django_rag.wsgi:application --bind 0.0.0.0:$PORT --workers 4"
