# Railway Nixpacks Configuration - Fixed Python Environment
# Ensure proper virtual environment setup and C++ libraries

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = ["python312", "gcc", "pkg-config", "stdenv.cc.cc.lib"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    ". /opt/venv/bin/activate && python manage.py collectstatic --noinput --clear"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn django_rag.wsgi"
