# Railway Nixpacks Configuration - Minimal and Stable
# Focus on Python 3.12 with essential build tools

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = ["python312", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput --clear"
]

[start]
cmd = "gunicorn django_rag.wsgi:application --bind 0.0.0.0:$PORT --workers 4"
