# Generated by Django 4.2 on 2025-09-02 16:14

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedding',
            name='vector_data',
        ),
        migrations.AddField(
            model_name='embedding',
            name='vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
